bot:
  token: my_token
  prefix: !

lavalink:
  nodes:
    - name: lavalink-node-1
      url: wss://localhost:9000
      password: TheWorldsBestPassword

permissions:
  enabled: false
  roles:
    - some_role_id

#sentry:
  #dsn: my_sentry_dsn

management.endpoints.web.exposure.include: prometheus