bot:
  token: my_token
  client-id: my_client_id
  prefix: !

lavalink:
  nodes:
    - name: lavalink-node-1
      url: wss://localhost:9000
      password: TheWorldsBestPassword

#sentry:
  #dsn: my_sentry_dsn

services:
  metrics: true
  api: true

management.endpoints.web.exposure.include: prometheus